---
version: "3.7"
services:

  fanyi-slackbot:
    build:
      context: .
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/fanyi-slackbot:${VERSION}
    container_name: fanyi-slackbot
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048mb
    environment:
      VERSION: ${VERSION}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_REGION}
        #! Ensure this log group exists prior to deploying to ECS!
        awslogs-group: fanyi
        awslogs-stream-prefix: fanyi.slackbot
    volumes:
      - config_store:/store

volumes:
  config_store:
    name: config_store